# This is a basic workflow to help you get started with Actions

name: BirdTracks_CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, windows, x64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v4

      - name: Setup Unity Environment
        uses: game-ci/unity-setup@v1
        with:
          unityVersion: '2022.3.20f1'  # Specify your project's Unity version

      - name: Generate Library
        run: |
          # Add a command here to open Unity in batchmode to generate the Library directory
          # Example (adjust based on your actual Unity setup and version):
          "C:\Program Files\Unity\Hub\Editor\2020.3.0f1\Editor\Unity.exe" -batchmode -projectPath "${{ github.workspace }}/Birdtracks_SentisAI/Birdtracks_SentisAI" -quit

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Birdtracks_SentisAI/Birdtracks_SentisAI/Library
          key: Library-${{hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**')}}
          restore-keys: |
            Library-${{hashFiles('Assets/**')}}
            Library-

      - name: Build Project
        uses: game-ci/unity-builder@v4
        with:
          projectPath: Birdtracks_SentisAI/Birdtracks_SentisAI
          targetPlatform: StandaloneWindows64
      
